name: "Firewall"
version: "1.1.0"
api-version: "1.13"
description: "A firewall for bukkit servers."
author: "Sh99"
main: de.sh99.firewall.Firewall
load: STARTUP
commands:
  sh99:
    usage: "/sh99"
    description: "Use it with tabcomplete feature to access the whole sh99-library management."